### ISSUE TITLE
pdfpreview.php needs require_login/require_capability checks.

### ISSUE THREAD

**Issue by danmarsden** [SaseTRT15/certrt#1]
There are no user login checks, no checks to see if the user is able to view the related course, no checks on activity completion etc. If this file is only for admin/teaching staff you should add login and capability checks to prevent users from generating certificates they are not eligible for. At the moment, any user can create and print any certificate they want.

**Comment by vmfvmf** [comment]
I thought it wasnt needed, because it was just to preview how a certificate would looks like, but, some bad intentioned users could make harmfull use of it editing the information before printing, the certificates aren't created at that moment and even got serial numbers but are easily edited.

The corrections will be done, thanks for the report :)

**Comment by vmfvmf** [comment]
Done :)
